"""
Pytest Export Generator
Converts test cases JSON to executable pytest code
Supports: Pytest, Gherkin, RTM export formats
"""

from typing import List, Dict, Any, Optional
import json
from datetime import datetime


class PytestExportGenerator:
    """Generate executable pytest code from test cases"""
    
    def __init__(self, test_data: Dict[str, Any]):
        """
        Args:
            test_data: Output from AITestCaseGeneratorV3.generate()
        """
        self.test_data = test_data
        self.detailed = test_data.get('detailed', [])
        self.timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    def generate_pytest_file(self) -> str:
        """Generate complete pytest file"""
        code = self._generate_header()
        code += self._generate_imports()
        code += self._generate_fixtures()
        code += self._generate_test_classes()
        code += self._generate_helper_functions()
        return code
    
    def _generate_header(self) -> str:
        """Generate file header with metadata"""
        header = f'''"""
Pytest Test Suite - Auto-generated from Requirements
Generated: {self.timestamp}
Total Requirements: {len(self.detailed)}
Total Test Cases: {sum(r.get('test_cases_count', 0) for r in self.detailed)}
Average Confidence: {self.test_data.get('avg_nlp_confidence', 0):.1%}

Generated by: AI Test Case Generator v3
This file contains executable pytest test cases ready for CI/CD pipeline
"""

import pytest
import json
from datetime import datetime, timedelta
from typing import Dict, Any, List, Optional
from dataclasses import dataclass
from enum import Enum
import sys
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Test configuration
TEST_TIMEOUT = 30
BASE_URL = "http://localhost:8000"
RETRY_ATTEMPTS = 3
RETRY_DELAY = 0.5

'''
        return header
    
    def _generate_imports(self) -> str:
        """Generate import statements"""
        return '''
# API Client (adjust based on your API framework)
class APIClient:
    """Mock API client - replace with actual implementation"""
    def __init__(self, base_url: str = BASE_URL):
        self.base_url = base_url
        self.session_data = {}
    
    def create_booking(self, payload: Dict) -> Dict:
        """Create new room booking"""
        # TODO: Implement actual API call
        return {
            "status_code": 200,
            "data": {
                "status": "success",
                "booking_id": "BK-001-2026-04-02",
                "confirmation_email_sent": True
            }
        }
    
    def confirm_booking(self, booking_id: str) -> Dict:
        """Confirm booking"""
        return {"status_code": 200, "data": {"state": "confirmed"}}
    
    def check_in(self, booking_id: str) -> Dict:
        """Check-in guest"""
        return {"status_code": 200, "data": {"state": "checked_in"}}
    
    def check_out(self, booking_id: str) -> Dict:
        """Check-out guest"""
        return {"status_code": 200, "data": {"state": "checked_out"}}
    
    def get_room_price(self, room_type: str) -> Dict:
        """Get room pricing"""
        prices = {
            "Single": {"status_code": 200, "data": {"price": 600000}},
            "Deluxe": {"status_code": 200, "data": {"price": 1200000}},
            "Suite": {"status_code": 200, "data": {"price": 2500000}}
        }
        return prices.get(room_type, {"status_code": 400, "data": {}})
    
    def process_payment(self, payload: Dict) -> Dict:
        """Process payment"""
        # Check for SQL injection attempts
        if payload.get("customer_id") and ("'" in str(payload.get("customer_id")) or 
                                           "OR" in str(payload.get("customer_id")).upper()):
            return {"status_code": 400, "data": {"error": "Invalid input"}}
        
        # Check for XSS attempts
        card_holder = payload.get("card_holder", "")
        if "<script>" in card_holder.lower() or "</script>" in card_holder.lower():
            return {"status_code": 400, "data": {"error": "Invalid input"}}
        
        return {"status_code": 200, "data": {"transaction_id": "TXN-001"}}

'''
    
    def _generate_fixtures(self) -> str:
        """Generate pytest fixtures"""
        return '''
@pytest.fixture(scope="session")
def api_client():
    """Global API client fixture"""
    return APIClient(base_url=BASE_URL)

@pytest.fixture(scope="function")
def sample_booking_payload():
    """Sample booking data"""
    return {
        "room_type": "Deluxe",
        "check_in_date": "2026-04-10",
        "check_out_date": "2026-04-15",
        "customer_name": "Nguyễn Văn A",
        "phone": "0901234567",
        "email": "customer@example.com"
    }

@pytest.fixture(scope="function")
def booking_with_discount(sample_booking_payload):
    """Booking with discount applied"""
    booking = sample_booking_payload.copy()
    booking["discount_code"] = "NEW2026"
    booking["discount_percent"] = 10
    return booking

'''
    
    def _generate_test_classes(self) -> str:
        """Generate test classes for each requirement"""
        code = ""
        
        for req in self.detailed:
            req_id = req.get('requirement_id', f"REQ-{req.get('index')}")
            req_text = req.get('requirement', "")
            test_cases = req.get('test_cases', [])
            
            if not test_cases:
                continue
            
            # Create class name from requirement
            class_name = f"Test{req_id.replace('-', '_')}"
            
            code += f'''
class {class_name}:
    """
    Requirement: {req_text}
    ID: {req_id}
    Test Cases: {len(test_cases)}
    Average Confidence: {req.get('nlp_confidence', 0):.1%}
    """
'''
            
            # Generate test methods
            for tc in test_cases:
                tc_id = tc.get('id', 'TC-UNKNOWN')
                tc_type = tc.get('type', 'functional')
                tc_title = tc.get('title', 'Test Case')
                confidence = tc.get('confidence', 0.85)
                
                code += f'''
    def test_{tc_id.lower().replace('-', '_')}(self, api_client, sample_booking_payload):
        """
        Test ID: {tc_id}
        Type: {tc_type}
        Title: {tc_title}
        Priority: {tc.get('priority', 'MEDIUM')}
        Confidence: {confidence:.1%}
        """
        try:
            # Setup
            payload = sample_booking_payload.copy()
            
            # Execute
            response = api_client.create_booking(payload)
            
            # Validate
            assert response['status_code'] == 200, f"Expected 200, got {{response['status_code']}}"
            assert response['data']['status'] == 'success', "Booking creation failed"
            assert response['data'].get('booking_id') is not None, "No booking ID returned"
            
            logger.info(f"✓ {{tc_id}} passed")
        except AssertionError as e:
            logger.error(f"✗ {{tc_id}} failed: {{e}}")
            raise
        except Exception as e:
            logger.error(f"✗ {{tc_id}} error: {{e}}")
            raise

'''
        
        return code
    
    def _generate_helper_functions(self) -> str:
        """Generate helper functions and utilities"""
        return '''
# ===== HELPER FUNCTIONS =====

def retry_api_call(func, max_retries=RETRY_ATTEMPTS):
    """Retry API calls with exponential backoff"""
    for attempt in range(max_retries):
        try:
            return func()
        except Exception as e:
            if attempt == max_retries - 1:
                raise
            wait_time = RETRY_DELAY * (2 ** attempt)
            logger.warning(f"Retry {attempt + 1}/{max_retries} after {wait_time}s: {e}")
            import time
            time.sleep(wait_time)

@pytest.mark.parametrize("room_type,expected_price_min,expected_price_max", [
    ("Single", 500000, 700000),
    ("Deluxe", 1000000, 1500000),
    ("Suite", 2000000, 3000000)
])
def test_room_pricing_equivalence_partition(api_client, room_type, expected_price_min, expected_price_max):
    """Equivalence Partition: Test room pricing by category"""
    response = api_client.get_room_price(room_type)
    
    assert response['status_code'] == 200
    price = response['data'].get('price')
    assert expected_price_min <= price <= expected_price_max, \\
        f"Price {price} outside range [{expected_price_min}, {expected_price_max}]"

def test_payment_sql_injection_protection(api_client):
    """Security Test: SQL Injection Protection"""
    malicious_payload = {
        "customer_id": "1' OR '1'='1",
        "amount": 1000000
    }
    
    response = api_client.process_payment(malicious_payload)
    assert response['status_code'] == 400, "SQL injection should be rejected"

def test_payment_xss_protection(api_client):
    """Security Test: XSS Protection"""
    payload = {
        "card_holder": "<script>alert('xss')</script>",
        "amount": 1000000
    }
    
    response = api_client.process_payment(payload)
    assert response['status_code'] == 400, "XSS payload should be rejected"

# ===== PYTEST CONFIGURATION =====

def pytest_configure(config):
    """Configure pytest"""
    config.addinivalue_line(
        "markers", "slow: marks tests as slow"
    )
    config.addinivalue_line(
        "markers", "security: marks tests as security-related"
    )
    config.addinivalue_line(
        "markers", "integration: marks tests as integration tests"
    )

if __name__ == "__main__":
    # Run tests with: python test_hotel_booking.py
    pytest.main([__file__, "-v", "--tb=short"])
'''
    
    def export_gherkin_file(self) -> str:
        """Generate Gherkin/BDD feature files"""
        gherkin = f'''# Generated from Requirements
# Created: {self.timestamp}
# Total Features: {len(self.detailed)}

'''
        
        for req in self.detailed:
            req_text = req.get('requirement', "")
            test_cases = req.get('test_cases', [])
            
            if not test_cases:
                continue
            
            # Extract main action/feature
            feature_name = req_text[:50].strip()
            
            gherkin += f'''
Feature: {feature_name}
  Background:
    Given the system is running
    And the database is initialized

'''
            
            for tc in test_cases:
                tc_type = tc.get('type', 'functional')
                tc_title = tc.get('title', 'Test Case')
                priority = tc.get('priority', 'MEDIUM')
                
                if tc_type == 'happy_path':
                    gherkin += f'''  @{priority.lower()} @happy_path
  Scenario: {tc_title}
    Given customer is on booking page
    When customer selects a room
    And customer enters check-in and check-out dates
    And customer confirms booking
    Then system creates booking successfully
    And confirmation email is sent
    And booking ID is returned

'''
                elif tc_type == 'negative':
                    gherkin += f'''  @{priority.lower()} @negative
  Scenario: {tc_title}
    Given customer is on booking page
    When customer tries to submit form with missing fields
    Then system displays validation error
    And booking is not created

'''
                elif tc_type == 'boundary_value':
                    gherkin += f'''  @{priority.lower()} @boundary
  Scenario: {tc_title}
    Given the system limits concurrent transactions to 100
    When 100 concurrent booking requests are submitted
    Then all requests are processed successfully
    And response time is within SLA

'''
            
            gherkin += "\n"
        
        return gherkin
    
    def export_rtm_csv(self) -> str:
        """Export Requirements Traceability Matrix as CSV"""
        csv = "Requirement ID,Requirement Text,Happy Path,Negative,Boundary,State,Effort (h),Confidence,Status\n"
        
        for req in self.detailed:
            req_id = req.get('requirement_id', f"REQ-{req.get('index')}")
            req_text = req.get('requirement', '').replace(',', ';')
            test_cases = req.get('test_cases', [])
            
            # Count test types
            test_types = {}
            for tc in test_cases:
                tc_type = tc.get('type', 'other')
                test_types[tc_type] = test_types.get(tc_type, 0) + 1
            
            happy = "✓" if test_types.get('happy_path', 0) > 0 else "✗"
            negative = "✓" if test_types.get('negative', 0) > 0 else "✗"
            boundary = "✓" if test_types.get('boundary_value', 0) > 0 else "✗"
            state = "✓" if test_types.get('state_transition', 0) > 0 else "✗"
            
            status = "100%" if all([happy == "✓", negative == "✓"]) else "Partial"
            
            csv += f'{req_id},"{req_text}",{happy},{negative},{boundary},{state},{len(test_cases)},{req.get("nlp_confidence", 0):.1%},{status}\n'
        
        return csv
    
    def export_json_detailed(self) -> str:
        """Export test cases as detailed JSON"""
        return json.dumps(self.test_data, indent=2, ensure_ascii=False)
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get export statistics"""
        all_tests = []
        test_type_count = {}
        priority_count = {}
        
        for req in self.detailed:
            for tc in req.get('test_cases', []):
                all_tests.append(tc)
                tc_type = tc.get('type', 'other')
                test_type_count[tc_type] = test_type_count.get(tc_type, 0) + 1
                
                priority = tc.get('priority', 'MEDIUM')
                priority_count[priority] = priority_count.get(priority, 0) + 1
        
        return {
            "total_requirements": len(self.detailed),
            "total_test_cases": len(all_tests),
            "average_confidence": self.test_data.get('avg_nlp_confidence', 0),
            "test_type_distribution": test_type_count,
            "priority_distribution": priority_count,
            "status": "ready_for_execution"
        }
