"""
QA Studio router — visualises the new 4-stage QA pipeline.

Endpoints
---------
GET  /testcase/qa-studio                     — HTML studio
POST /api/v3/qa-pipeline/generate            — JSON in/out, run pipeline
POST /api/v3/qa-pipeline/generate-from-file  — multipart file upload
POST /api/v3/qa-pipeline/export-pytest       — return pytest test file
"""
from __future__ import annotations

import io
import textwrap
from typing import Optional

from fastapi import APIRouter, File, Form, UploadFile
from fastapi.responses import HTMLResponse, JSONResponse, PlainTextResponse
from pydantic import BaseModel

from .task_gen.qa_pipeline import QAPipeline


router = APIRouter(tags=["qa-pipeline"])
_PIPELINE = QAPipeline()


# ─────────────────────────────────────────────────────────────────────────
class GenerateRequest(BaseModel):
    text: str
    max_scenarios: Optional[int] = 8


@router.post("/api/v3/qa-pipeline/generate")
def qa_generate(req: GenerateRequest):
    pipeline = _PIPELINE if req.max_scenarios in (None, 8) else QAPipeline(
        max_scenarios_per_req=req.max_scenarios
    )
    out = pipeline.run(req.text or "")
    return JSONResponse(out.to_dict())


@router.post("/api/v3/qa-pipeline/generate-from-file")
async def qa_generate_file(
    file: UploadFile = File(...),
    max_scenarios: int = Form(8),
):
    raw = await file.read()
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        text = raw.decode("latin-1", errors="ignore")
    pipeline = QAPipeline(max_scenarios_per_req=max_scenarios)
    out = pipeline.run(text)
    return JSONResponse(out.to_dict())


# ── pytest export ─────────────────────────────────────────────────────────
def _to_pyident(s: str) -> str:
    import re as _re
    s = _re.sub(r"[^0-9A-Za-z]+", "_", s).strip("_").lower()
    return s or "case"


@router.post("/api/v3/qa-pipeline/export-pytest")
def qa_export_pytest(req: GenerateRequest):
    out = _PIPELINE.run(req.text or "")
    lines = [
        '"""Auto-generated by QA Pipeline v3."""',
        "import pytest",
        "",
    ]
    for tc in out.test_cases:
        fn = f"test_{_to_pyident(tc.test_id)}_{_to_pyident(tc.title)[:40]}"
        lines.append(f"def {fn}():")
        lines.append(f'    """{tc.title}')
        lines.append(f"    ID: {tc.test_id} | Priority: {tc.priority} "
                     f"| Category: {tc.category.value}")
        if tc.requirement_ref:
            lines.append(f"    Ref: {tc.requirement_ref}")
        lines.append('    """')
        if tc.preconditions:
            lines.append("    # Preconditions")
            for p in tc.preconditions:
                lines.append(f"    # - {p}")
        for i, st in enumerate(tc.steps, 1):
            lines.append(f"    # Step {i}: {st.action}")
            lines.append(f"    # Expected: {st.expected}")
        lines.append(f"    # Final expected: {tc.expected_result}")
        lines.append("    pytest.skip('Auto-generated stub — implement me')")
        lines.append("")
    return PlainTextResponse(
        "\n".join(lines),
        headers={"Content-Disposition": 'attachment; filename="qa_pipeline_tests.py"'},
        media_type="text/x-python",
    )


# ─────────────────────────────────────────────────────────────────────────
@router.get("/testcase/qa-studio", response_class=HTMLResponse)
def qa_studio_page():
    return HTMLResponse(_STUDIO_HTML)


_STUDIO_HTML = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>QA Studio v3 · 4-stage pipeline</title>
<meta name="viewport" content="width=device-width,initial-scale=1">
<style>
  :root{
    --bg:#0f172a; --panel:#172033; --panel2:#1e293b; --line:#243049;
    --text:#e2e8f0; --muted:#94a3b8; --accent:#7c3aed; --accent2:#22d3ee;
    --green:#22c55e; --amber:#f59e0b; --red:#ef4444; --pink:#ec4899;
  }
  *{box-sizing:border-box}
  body{margin:0;font-family:ui-sans-serif,system-ui,-apple-system,Segoe UI,
        Roboto,sans-serif;background:linear-gradient(180deg,#0b1022,#0f172a);
        color:var(--text);min-height:100vh}
  header{padding:18px 28px;border-bottom:1px solid var(--line);
          display:flex;align-items:center;gap:14px;backdrop-filter:blur(8px);
          background:rgba(15,23,42,.7);position:sticky;top:0;z-index:10}
  header h1{margin:0;font-size:20px;font-weight:700;
            background:linear-gradient(90deg,#a78bfa,#22d3ee);
            -webkit-background-clip:text;color:transparent}
  header .pill{font-size:11px;padding:3px 10px;border-radius:999px;
                background:#312e81;color:#c4b5fd;font-weight:600}
  main{display:grid;grid-template-columns:380px 1fr;gap:20px;padding:20px}
  @media (max-width:1024px){main{grid-template-columns:1fr}}
  .card{background:var(--panel);border:1px solid var(--line);
        border-radius:14px;padding:18px;box-shadow:0 1px 0 rgba(255,255,255,.03) inset}
  .card h2{margin:0 0 12px;font-size:14px;letter-spacing:.04em;
            text-transform:uppercase;color:var(--muted)}
  textarea{width:100%;min-height:240px;border-radius:10px;
            border:1px solid var(--line);background:#0b1022;color:var(--text);
            padding:12px;font:13px/1.5 ui-monospace,Menlo,monospace;resize:vertical}
  .row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}
  button{cursor:pointer;border:0;padding:10px 16px;border-radius:10px;
          background:linear-gradient(90deg,#7c3aed,#22d3ee);color:white;
          font-weight:600;transition:transform .1s,box-shadow .2s}
  button:hover{transform:translateY(-1px);box-shadow:0 6px 20px rgba(124,58,237,.4)}
  button.ghost{background:transparent;border:1px solid var(--line);color:var(--text)}
  button:disabled{opacity:.5;cursor:not-allowed;transform:none}
  input[type=number]{width:70px;padding:8px;border-radius:8px;
                     border:1px solid var(--line);background:#0b1022;color:var(--text)}
  label{font-size:12px;color:var(--muted)}
  .stats{display:grid;grid-template-columns:repeat(4,1fr);gap:10px;margin-bottom:16px}
  @media(max-width:768px){.stats{grid-template-columns:repeat(2,1fr)}}
  .stat{background:var(--panel2);border:1px solid var(--line);
        border-radius:10px;padding:12px}
  .stat .v{font-size:22px;font-weight:700;color:#a78bfa}
  .stat .k{font-size:11px;color:var(--muted);text-transform:uppercase;
            letter-spacing:.05em;margin-top:2px}
  .req{background:var(--panel);border:1px solid var(--line);
        border-radius:14px;margin-bottom:14px;overflow:hidden}
  .req-head{padding:14px 18px;background:linear-gradient(90deg,#1e1b4b,#172033);
            border-bottom:1px solid var(--line);display:flex;
            justify-content:space-between;align-items:center;flex-wrap:wrap;gap:10px}
  .req-head .raw{font-size:14px;font-weight:600;flex:1}
  .badges{display:flex;gap:6px;flex-wrap:wrap}
  .badge{font-size:10px;padding:3px 9px;border-radius:999px;
          background:#312e81;color:#c4b5fd;font-weight:600;letter-spacing:.04em}
  .badge.dom{background:#064e3b;color:#6ee7b7}
  .badge.cmp-low{background:#064e3b;color:#6ee7b7}
  .badge.cmp-medium{background:#7c2d12;color:#fdba74}
  .badge.cmp-high{background:#7f1d1d;color:#fca5a5}
  .badge.cat-happy_path{background:#064e3b;color:#6ee7b7}
  .badge.cat-negative{background:#7f1d1d;color:#fca5a5}
  .badge.cat-boundary{background:#713f12;color:#fcd34d}
  .badge.cat-security{background:#831843;color:#f9a8d4}
  .badge.cat-permission{background:#1e3a8a;color:#93c5fd}
  .badge.cat-performance{background:#3b0764;color:#d8b4fe}
  .badge.cat-edge_case{background:#0e7490;color:#67e8f9}
  .badge.cat-integration{background:#365314;color:#bef264}
  .badge.cat-data_integrity{background:#7c2d12;color:#fdba74}
  .req-body{padding:14px 18px}
  .req-grid{display:grid;grid-template-columns:200px 1fr;gap:8px 16px;
            font-size:13px;margin-bottom:14px}
  .req-grid .lbl{color:var(--muted);text-transform:uppercase;
                  letter-spacing:.04em;font-size:11px;padding-top:2px}
  .testcase{background:var(--panel2);border:1px solid var(--line);
            border-radius:10px;margin-top:10px;overflow:hidden}
  .tc-head{padding:10px 14px;display:flex;justify-content:space-between;
            align-items:center;cursor:pointer;gap:10px;flex-wrap:wrap;
            background:rgba(124,58,237,.05)}
  .tc-head:hover{background:rgba(124,58,237,.12)}
  .tc-id{font:11px ui-monospace,monospace;color:var(--accent2)}
  .tc-title{font-weight:600;flex:1;min-width:200px}
  .tc-q{font-size:11px;padding:2px 8px;border-radius:6px;font-weight:700}
  .q-hi{background:#064e3b;color:#6ee7b7}
  .q-md{background:#713f12;color:#fcd34d}
  .q-lo{background:#7f1d1d;color:#fca5a5}
  .tc-body{padding:12px 14px;border-top:1px solid var(--line);display:none;
            font-size:13px}
  .tc-body.open{display:block}
  .tc-body table{width:100%;border-collapse:collapse;margin:6px 0}
  .tc-body th,.tc-body td{text-align:left;padding:6px 8px;
                          border-bottom:1px solid var(--line);vertical-align:top}
  .tc-body th{color:var(--muted);font-size:11px;text-transform:uppercase;
              letter-spacing:.05em;font-weight:600}
  .gwt{display:grid;grid-template-columns:60px 1fr;gap:4px 10px;font-size:12px;
        margin:8px 0;padding:8px 10px;background:#0b1022;border-radius:6px}
  .gwt .k{color:#a78bfa;font-weight:700}
  .empty{text-align:center;padding:60px 20px;color:var(--muted)}
  .empty .big{font-size:42px;margin-bottom:10px}
  .pre-list{margin:0;padding-left:18px;font-size:12px;color:var(--muted)}
  .toolbar{display:flex;gap:8px;margin-bottom:12px;flex-wrap:wrap}
  .filter{font-size:12px;padding:6px 10px;border-radius:8px;
          background:var(--panel2);border:1px solid var(--line);
          color:var(--muted);cursor:pointer}
  .filter.active{background:var(--accent);color:white;border-color:var(--accent)}
  .progress{height:6px;background:var(--line);border-radius:3px;overflow:hidden;
            margin-top:6px}
  .progress > div{height:100%;background:linear-gradient(90deg,#22d3ee,#a78bfa);
                  transition:width .4s}
  .err{color:var(--red);font-size:13px;margin-top:8px}
</style>
</head>
<body>

<header>
  <h1>🧪 QA Studio</h1>
  <span class="pill">v3 · 4-stage pipeline</span>
  <span style="margin-left:auto;font-size:12px;color:var(--muted)">
    Parser → Scenarios → Builder → Enhancer
  </span>
</header>

<main>

  <section class="card">
    <h2>📥 Requirements</h2>
    <textarea id="reqInput" placeholder="One requirement per line, e.g.
Patient books an appointment with a selected doctor.
Payment must be encrypted in transit and at rest.
Login must respond in under 2 seconds for 100 concurrent users."></textarea>

    <div class="row" style="margin-top:12px">
      <label>Max scenarios / req:</label>
      <input id="maxSc" type="number" value="8" min="3" max="20">
      <button id="runBtn">⚡ Generate</button>
      <button id="loadDemoBtn" class="ghost">📂 Load demo</button>
      <button id="exportBtn" class="ghost" disabled>⬇ pytest</button>
    </div>
    <div id="errBox" class="err"></div>

    <div style="margin-top:18px">
      <label style="font-weight:600">Or upload a file</label>
      <input id="fileInput" type="file" accept=".txt,.md,.csv"
              style="margin-top:6px;width:100%">
    </div>

    <div style="margin-top:20px;font-size:11px;color:var(--muted);
                line-height:1.6">
      <strong style="color:#a78bfa">How it works</strong><br>
      1. <b>Parser</b> extracts actor, intent, entities, NFRs &amp; edge cases<br>
      2. <b>Scenarios</b> generate happy/negative/boundary/security/perf<br>
      3. <b>Builder</b> turns each scenario into executable steps<br>
      4. <b>Enhancer</b> cleans text and scores quality
    </div>
  </section>

  <section>
    <div id="output">
      <div class="empty">
        <div class="big">🚀</div>
        Paste requirements on the left, hit <b>Generate</b>, and watch the
        pipeline produce executable test cases in milliseconds.
      </div>
    </div>
  </section>

</main>

<script>
const DEMO = `Patient must register an account with email verification before booking.
Patient books an appointment with a selected doctor and time slot.
The system shall reject booking when the slot is already taken.
The login endpoint must respond in under 2 seconds for 100 concurrent users.
Payment must be encrypted in transit and at rest.
Admin can view audit logs but cannot modify them.`;

const $ = s => document.querySelector(s);
const $$ = s => document.querySelectorAll(s);
let LAST = null;

$('#loadDemoBtn').onclick = () => $('#reqInput').value = DEMO;

$('#runBtn').onclick = async () => {
  const text = $('#reqInput').value.trim();
  if (!text) { showError('Please enter at least one requirement.'); return; }
  showError('');
  $('#runBtn').disabled = true; $('#runBtn').textContent = '⏳ Generating…';
  try {
    const r = await fetch('/api/v3/qa-pipeline/generate', {
      method: 'POST', headers: {'Content-Type':'application/json'},
      body: JSON.stringify({text, max_scenarios: parseInt($('#maxSc').value)||8})
    });
    if (!r.ok) throw new Error('HTTP '+r.status);
    LAST = await r.json();
    render(LAST);
    $('#exportBtn').disabled = false;
  } catch(e) { showError(e.message); }
  finally { $('#runBtn').disabled = false; $('#runBtn').textContent = '⚡ Generate'; }
};

$('#fileInput').onchange = async (e) => {
  const f = e.target.files[0]; if (!f) return;
  const fd = new FormData(); fd.append('file', f);
  fd.append('max_scenarios', $('#maxSc').value || 8);
  $('#runBtn').disabled = true;
  try {
    const r = await fetch('/api/v3/qa-pipeline/generate-from-file',
                         {method:'POST', body: fd});
    LAST = await r.json(); render(LAST); $('#exportBtn').disabled = false;
  } catch(e) { showError(e.message); }
  finally { $('#runBtn').disabled = false; }
};

$('#exportBtn').onclick = async () => {
  const text = $('#reqInput').value.trim(); if (!text) return;
  const r = await fetch('/api/v3/qa-pipeline/export-pytest', {
    method:'POST', headers:{'Content-Type':'application/json'},
    body: JSON.stringify({text})
  });
  const blob = await r.blob();
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = 'qa_pipeline_tests.py';
  a.click();
};

function showError(msg){ $('#errBox').textContent = msg; }

function escapeHtml(s){
  return (s||'').replace(/[&<>"']/g, c => ({
    '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
}

function qBadge(q){
  const cls = q >= 0.8 ? 'q-hi' : q >= 0.6 ? 'q-md' : 'q-lo';
  return `<span class="tc-q ${cls}">Q ${(q*100).toFixed(0)}</span>`;
}

function render(data){
  const out = $('#output');
  const s = data.stats;
  let html = `
    <div class="stats">
      <div class="stat"><div class="v">${s.requirements}</div>
        <div class="k">Requirements</div></div>
      <div class="stat"><div class="v">${s.scenarios}</div>
        <div class="k">Scenarios</div></div>
      <div class="stat"><div class="v">${s.test_cases}</div>
        <div class="k">Test cases</div></div>
      <div class="stat"><div class="v">${(s.avg_quality_score*100).toFixed(0)}%</div>
        <div class="k">Avg quality</div>
        <div class="progress"><div style="width:${s.avg_quality_score*100}%"></div></div>
      </div>
    </div>`;

  // category chips
  html += `<div class="toolbar">`;
  for (const [k,v] of Object.entries(s.by_category||{})){
    html += `<span class="badge cat-${k}">${k} · ${v}</span>`;
  }
  html += `<span style="flex:1"></span>
           <span style="font-size:11px;color:var(--muted)">
             Generated in ${s.elapsed_ms} ms</span></div>`;

  // group test cases per requirement
  const byReq = {};
  data.test_cases.forEach(tc => {
    (byReq[tc.requirement_ref] = byReq[tc.requirement_ref] || []).push(tc);
  });

  data.parsed.forEach((p, idx) => {
    const ref = `REQ-${String(idx+1).padStart(3,'0')}`;
    const cases = byReq[ref] || [];
    const cmp = p.complexity || 'medium';
    html += `
      <div class="req">
        <div class="req-head">
          <div class="raw">${escapeHtml(p.raw)}</div>
          <div class="badges">
            <span class="badge dom">${escapeHtml(p.domain||'General')}</span>
            <span class="badge cmp-${cmp}">${cmp}</span>
            <span class="badge">conf ${(p.confidence*100).toFixed(0)}%</span>
            ${(p.nfr_tags||[]).map(t=>`<span class="badge">${escapeHtml(t)}</span>`).join('')}
          </div>
        </div>
        <div class="req-body">
          <div class="req-grid">
            <div class="lbl">Actor</div><div>${escapeHtml(p.actor||'—')}</div>
            <div class="lbl">Intent</div><div>${escapeHtml(p.intent||'—')}</div>
            <div class="lbl">Entities</div><div>${(p.entities||[]).map(e=>`<code>${escapeHtml(e)}</code>`).join(' ') || '—'}</div>
            <div class="lbl">Constraints</div><div>${(p.constraints||[]).map(escapeHtml).join('<br>') || '—'}</div>
            <div class="lbl">Edge cases</div><div>${(p.edge_cases||[]).map(escapeHtml).join('<br>') || '—'}</div>
          </div>
          ${cases.map(renderTC).join('')}
        </div>
      </div>`;
  });

  out.innerHTML = html;

  $$('.tc-head').forEach(h => h.onclick = () => {
    h.nextElementSibling.classList.toggle('open');
  });
}

function renderTC(tc){
  const steps = (tc.steps||[]).map((s,i)=>`
    <tr><td>${i+1}</td><td>${escapeHtml(s.action)}</td>
        <td>${escapeHtml(s.expected)}</td></tr>`).join('');
  const tdRows = Object.entries(tc.test_data||{}).map(
    ([k,v])=>`<tr><td><code>${escapeHtml(k)}</code></td>
              <td>${escapeHtml(typeof v==='object'?JSON.stringify(v):String(v))}</td></tr>`
  ).join('');
  const cat = tc.category || 'happy_path';
  return `
    <div class="testcase">
      <div class="tc-head">
        <span class="tc-id">${escapeHtml(tc.test_id)}</span>
        <span class="tc-title">${escapeHtml(tc.title)}</span>
        <span class="badge cat-${cat}">${cat}</span>
        <span class="badge">${escapeHtml(tc.priority)}</span>
        ${qBadge(tc.quality_score||0)}
      </div>
      <div class="tc-body">
        ${tc.preconditions?.length?`<b>Preconditions</b>
           <ul class="pre-list">${tc.preconditions.map(p=>`<li>${escapeHtml(p)}</li>`).join('')}</ul>`:''}
        <table>
          <thead><tr><th>#</th><th>Action</th><th>Expected</th></tr></thead>
          <tbody>${steps}</tbody>
        </table>
        ${tdRows?`<b>Test data</b><table>${tdRows}</table>`:''}
        ${tc.expected_result?`<div class="gwt">
          <span class="k">Result</span><span>${escapeHtml(tc.expected_result)}</span>
        </div>`:''}
        ${tc.postconditions?.length?`<b>Postconditions</b>
           <ul class="pre-list">${tc.postconditions.map(p=>`<li>${escapeHtml(p)}</li>`).join('')}</ul>`:''}
      </div>
    </div>`;
}
</script>
</body>
</html>"""
